---
title: "DCE Metrics Analysis, flow"
output: word_document
date: "2024-02-23"
---
```{r}
library(tidyverse)
library(tidyr)
library(ggplot2)
```

Scenario 1: everyone
```{r}
m <- char_interact_model_all_responses
b <- matrix(m$coefficients)
V <- m$var

### find unique rows in the model matrix => measures 
### We have to identify them 
X <- unique(model.matrix(m)) 
## you could assign the rownames of X to the profile description here 
## or reorder them 
rownames(X) <- c("1. TP_PPV", "2. sens_acc", "3. TP_NNR", "4. TP_Fscore", "5. sens_NNR", "6. TP_spec or TP_PLR", "8. sens_spec or sens_PLR", "13. TP_FP", "16. sens_FP", "17. sens_PPV", "18. TP_acc", "19. sens_Fscore", "20. TP_NPV or TP_CC", "24. sens_NPV or sens_CC")


### The reference profile is 1, 0, 0, 0, 1 (sens/spec)
### So the contrast vector for it will be 
for (r in 1:nrow(X)){
  if(all(X[r, c("characteristic_1", "characteristic_2", "characteristic_31", "characteristic_4", "characteristic_5")] ==
          c(1, 0, 0, 0, 1))) {
    x0 <- X[r, , drop = FALSE]
    a0 <- t(x0)
  }
}

### For a single profile I would
### create the contrast vectors using sens/spec as the reference 
### (') means transpose
### (x' - a0) : in column form 
### (x' - a0)' = (x - x0): in row form 
### and then do the (x - x0)*b 
### But I can do this for all together by stacking the (x-x0) a matrix
A <- X - x0[rep(1, nrow(X)), ]

### The point estimate is then exp(A * b) 
theta <- A %*% b 
exp(theta)

### The variance of the first contrast would be 
### A[1,] %*% V %*% A[1,]'
a1 <- A[1, , drop = FALSE]
v1 <- a1 %*% V %*% t(a1)
se1 <- sqrt(v1)

### for all of them  
v <- c()
for (r in 1:nrow(A)) {
  a <- A[r, , drop = FALSE]
  v <- c(v,  a %*% V %*% t(a))
}
se <- sqrt(v)

### with CIs
low <- theta + qnorm(0.025) * se
high <- theta + qnorm(1 - 0.025) * se

log_results <- cbind(theta, low, high)
results <- format(exp(log_results), digits = 2, nsmall = 2)
measures <- c("TP + PPV", "sens + acc", "TP + NNR", "TP + Fscore", "sens + NNR", "TP + spec or TP + PLR", "sens + spec or sens + PLR", "TP + FP", "sens + FP", "sens + PPV", "TP + acc", "sens + Fscore", "TP + NPV or TP + CC", "sens + NPV or sens + CC")
results2 <- cbind(measures, results)
colnames(results) <- c("OR", "CI_low", "CI_high")
metrics_table <- as_tibble(results)
metrics_table <- data.frame(measures,metrics_table)
metrics_table$OR <- as.numeric(metrics_table$OR)
metrics_table$CI_low <- as.numeric(metrics_table$CI_low)
metrics_table$CI_high <- as.numeric(metrics_table$CI_high)
metrics_table <- metrics_table %>%
  arrange(desc(measures)) 

#metrics_table <- unite(metrics_table, "95%CI", "95%CI low":"95%CI high", sep = '-', remove = TRUE)  

```
plot results
```{r}
scenario_1_measures <- ggplot(data=metrics_table, aes(x=reorder(measures, OR), y=OR)) +
  geom_bar(stat="identity", fill="steelblue4") +
  geom_errorbar(aes(ymin=CI_low, ymax=CI_high), width=.2) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "red") +  
  coord_flip() +
  scale_x_discrete(name = "Measure set") +
  scale_y_continuous(name="Predicted odds of being chosen (compared to sens + spec)", seq(0,4,0.5)) +
  theme_minimal() 
  
  scenario_1_measures


```

##Scenario 1: librarians
```{r}
m <- char_interact_model_librarians
b <- matrix(m$coefficients)
V <- m$var
X <- unique(model.matrix(m)) 
rownames(X) <- c("1. TP_PPV", "2. sens_acc", "3. TP_NNR", "4. TP_Fscore", "5. sens_NNR", "6. TP_spec or TP_PLR", "8. sens_spec or sens_PLR", "13. TP_FP", "16. sens_FP", "17. sens_PPV", "18. TP_acc", "19. sens_Fscore", "20. TP_NPV or TP_CC", "24. sens_NPV or sens_CC")


for (r in 1:nrow(X)){
  if(all(X[r, c("characteristic_1", "characteristic_2", "characteristic_31", "characteristic_4", "characteristic_5")] ==
          c(1, 0, 0, 0, 1))) {
    x0 <- X[r, , drop = FALSE]
    a0 <- t(x0)
  }
}

A <- X - x0[rep(1, nrow(X)), ]
theta <- A %*% b 
exp(theta)
v <- c()
for (r in 1:nrow(A)) {
  a <- A[r, , drop = FALSE]
  v <- c(v,  a %*% V %*% t(a))
}
se <- sqrt(v)

### with CIs
low <- theta + qnorm(0.025) * se
high <- theta + qnorm(1 - 0.025) * se

log_results <- cbind(theta, low, high)
results <- format(exp(log_results), digits = 2, nsmall = 2)

```

##Scenario 1: SRs
```{r}
m <- char_interact_model_sr
b <- matrix(m$coefficients)
V <- m$var
X <- unique(model.matrix(m)) 
rownames(X) <- c("1. sens-acc", "2. TP_PPV", "3. TP_NNR", "4. TP_Fscore", "5. sens_NNR", "6. TP_spec or TP_PLR", "7. sens_spec or sens_PLR", "11. TP_FP", "13. sens_FP", "15. sens_PPV", "16. TP_acc", "23. sens_NPV", "43. sens_fscore", "44. TP_NPV")


for (r in 1:nrow(X)){
  if(all(X[r, c("characteristic_1", "characteristic_2", "characteristic_31", "characteristic_4", "characteristic_5")] ==
          c(1, 0, 0, 0, 1))) {
    x0 <- X[r, , drop = FALSE]
    a0 <- t(x0)
  }
}

A <- X - x0[rep(1, nrow(X)), ]
theta <- A %*% b 
exp(theta)
v <- c()
for (r in 1:nrow(A)) {
  a <- A[r, , drop = FALSE]
  v <- c(v,  a %*% V %*% t(a))
}
se <- sqrt(v)

### with CIs
low <- theta + qnorm(0.025) * se
high <- theta + qnorm(1 - 0.025) * se

log_results <- cbind(theta, low, high)
results <- format(exp(log_results), digits = 2, nsmall = 2)

```